### ISSUE TITLE
Where could find the assignment5 on the web?

### ISSUE THREAD

**Issue by kugwzk** [Luvata/CS224N-2019#1]
Hi~
The assignment 5 of CS224N is required Stanford login but I still want to finish it. And I saw you maybe have the origin code of this assignment. Could you help me about it? 
Thanks a lot.

**Comment by Luvata** [comment]
I got A5 from [this](https://github.com/abgoswam/CS224N-Natural-Language-Processing-with-Deep-Learning/blob/master/a5-v1.2.zip) github repository. I haven't asked the author, but I think it's the origin code for this assignment
