### ISSUE TITLE
training args

### ISSUE THREAD

**Issue by qscez2001** [Luvata/CS224N-2019#4]
I ran sh run.sh train and I got an early stopping while loss is about 28.
It seems underfitting. 
Do you use the default arguments to train for the result?
I use the default and the BLEU score is far beneath 21.

**Comment by Luvata** [comment]
Can you provide me more information and procedure to reproduce that ?

**Comment by qscez2001** [comment]
I found the reason as same as this:
[https://github.com/ZacBi/CS224n-2019-solutions/issues/1](url)
Thanks a lot!
